--1
CREATE DATABASE DB_KEPEGAWAIAN
--
CREATE TABLE TABEL_KARYAWAN (KODE_KARYAWAN CHAR(10) PRIMARY KEY,
NAMA_KARYAWAN CHAR(20) NOT NULL, TEMPAT_LAHIR CHAR(10) NOT NULL, TANGGAL_LAHIR DATE NOT NULL, JENIS_KELAMIN CHAR(10) NOT NULL, ALAMAT CHAR(50) NOT NULL, NOMOR_TELEPON CHAR(15) NOT NULL, PENDIDIKAN_TERAKHIR CHAR(10) NOT NULL, TANGGAL_MULAI_KERJA DATE NOT NULL);
CREATE TABLE TABEL_JABATAN (KODE_JABATAN CHAR(10) PRIMARY KEY,
JABATAN CHAR(10) NOT NULL, GAJI_POKOK MONEY NOT NULL, TUNJANGAN MONEY NOT NULL, TRANSPORT MONEY NOT NULL);
CREATE TABLE TABEL_KELUARGA_KARYAWAN (KODE_KARYAWAN CHAR(10) NOT NULL, NAMA_KELUARGA CHAR(20) NOT NULL, 
HUBUNGAN CHAR(10) NOT NULL, TEMPAT_LAHIR CHAR(10) NOT NULL, TANGGAL_LAHIR DATE NOT NULL, PENDIDIKAN_TERAKHIR CHAR(10) NOT NULL);
CREATE TABLE TABEL_ADMINISTRASI (KODE_KARYAWAN CHAR(10) NOT NULL,
KODE_JABATAN CHAR(10) NOT NULL, JUMLAH_HARI_KERJA INT NOT NULL);
--
CREATE PROC ISI_KARYAWAN @KY CHAR(10), @NK CHAR(10), @TL CHAR(10), @TGL DATE, @JK CHAR(10), @AL CHAR(50), @T CHAR(15), @PT CHAR(10), @TMK DATE AS IF EXISTS (SELECT * FROM TABEL_KARYAWAN WHERE KODE_KARYAWAN = @KY) 
PRINT 'KODE KARYAWAN SUDAH ADA' ELSE
INSERT INTO TABEL_KARYAWAN VALUES (@KY, @NK, @TL, @TGL, @JK, @AL, @T, @PT, @TMK) RETURN
CREATE PROC ISI_JABATAN @KJ CHAR(10), @J CHAR(10), @GP MONEY, @TUN MONEY, @TRAN MONEY  AS IF EXISTS (SELECT * FROM TABEL_JABATAN WHERE KODE_JABATAN = @KJ)
PRINT 'KODE JABATAN SUDAH ADA' ELSE
INSERT INTO TABEL_JABATAN VALUES (@KJ, @J, @GP, @TUN, @TRAN) RETURN
CREATE PROC ISI_KELUARGA_KARYAWAN @KY CHAR(10), @NK CHAR(20), @H CHAR(10), @TL CHAR(10), @TGL DATE, @PT CHAR(10) AS IF EXISTS (SELECT * FROM TABEL_KELUARGA_KARYAWAN WHERE KODE_KARYAWAN = @KY)
PRINT 'KODE KELUARGA KARYAWAN SUDAH ADA' ELSE
INSERT INTO TABEL_KELUARGA_KARYAWAN VALUES (@KY, @NK, @H, @TL, @TGL, @PT) RETURN
CREATE PROC ISI_ADMINISTRASI @KY CHAR(10), @KJ CHAR(10), @JHK INT AS IF EXISTS (SELECT * FROM TABEL_ADMINISTRASI WHERE KODE_KARYAWAN = @KY)
PRINT 'KODE ADMINISTRASI SUDAH ADA' ELSE
INSERT INTO TABEL_ADMINISTRASI VALUES (@KY, @KJ, @JHK) RETURN
--
EXEC ISI_KARYAWAN 'KY01', 'MICHAEL', 'BENGKULU', '12/05/2000', 'PRIA', 'PONDOK BAMBU', '02318432782', 'SMU', '05/08/2019'
EXEC ISI_KARYAWAN 'KY02', 'JORDAN', 'PURWOKERTO', '02/11/2000', 'PRIA', 'PONDOK GEDE', '08518432782', 'S1', '07/05/2019'
EXEC ISI_KARYAWAN 'KY03', 'RUSSEL', 'CILACAP', '01/24/2000', 'PRIA', 'PONDOK KECIL', '0892432782', 'S2', '05/13/2019'
EXEC ISI_KARYAWAN 'KY04', 'JOHHNY', 'NGUNJUK', '04/19/2000', 'PRIA', 'PONDOK APUS', '0232342152', 'S3', '10/18/2019'
EXEC ISI_KARYAWAN 'KY05', 'BEN', 'ACEH', '02/15/2000', 'PRIA', 'PONDOK KAYU', '0421213782', 'SMP', '11/18/2019'
--
EXEC ISI_JABATAN 'J001', 'GURU PERTAMA', 3000000, 150000, 20000
EXEC ISI_JABATAN 'J002', 'MANAJER', 35000000, 120000, 80000
EXEC ISI_JABATAN 'J003', 'HRD', 2500000, 550000, 720000
EXEC ISI_JABATAN 'J004', 'MARKETING', 89000000, 1230000, 40000
EXEC ISI_JABATAN 'J005', 'SUPERVISOR', 43000000, 850000, 25000
--
EXEC ISI_KELUARGA_KARYAWAN 'KY01', 'MEI', 'ISTRI', 'BANDUNG', '05/12/2000', 'S1'
EXEC ISI_KELUARGA_KARYAWAN 'KY02', 'JIMMY', 'ANAK', 'JAKARTA', '08/22/2000', 'S2'
EXEC ISI_KELUARGA_KARYAWAN 'KY03', 'EMMA', 'KAKEK', 'YOGYAKARTA', '10/16/2000', 'SMA'
EXEC ISI_KELUARGA_KARYAWAN 'KY04', 'WATSON', 'ANAK', 'PALEMBANG', '07/06/2000', 'D3'
EXEC ISI_KELUARGA_KARYAWAN 'KY05', 'JENIFER', 'PAMAN', 'MAKASAR', '09/03/2000', 'D2'
--
EXEC ISI_ADMINISTRASI 'KY01', 'J001', 12
EXEC ISI_ADMINISTRASI 'KY02', 'J002', 20
EXEC ISI_ADMINISTRASI 'KY03', 'J003', 18
EXEC ISI_ADMINISTRASI 'KY04', 'J004', 28
EXEC ISI_ADMINISTRASI 'KY05', 'J005', 4
--
ALTER TABLE TABEL_KARYAWAN ADD TOTAL_TRANSPORT MONEY;
--
CREATE PROC ISI_ADMINISTRASI_HITUNG @KY CHAR(10), @KJ CHAR(10), @JHK INT AS IF EXISTS (SELECT * FROM TABEL_ADMINISTRASI WHERE KODE_KARYAWAN = @KY)
PRINT 'KODE ADMINISTRASI SUDAH ADA' ELSE
INSERT INTO TABEL_ADMINISTRASI VALUES (@KY, @KJ, @JHK) 
UPDATE TABEL_KARYAWAN SET TOTAL_TRANSPORT = @JHK * TRANSPORT 
FROM TABEL_KARYAWAN, TABEL_JABATAN WHERE KODE_KARYAWAN = @KY AND KODE_JABATAN = @KJ RETURN
--
EXEC ISI_ADMINISTRASI_HITUNG 'KY01', 'J001', 12
EXEC ISI_ADMINISTRASI_HITUNG 'KY02', 'J002', 20
EXEC ISI_ADMINISTRASI_HITUNG 'KY03', 'J003', 18
EXEC ISI_ADMINISTRASI_HITUNG 'KY04', 'J004', 28
EXEC ISI_ADMINISTRASI_HITUNG 'KY05', 'J005', 4
--3
CREATE PROC TAMPIL_KARYAWAN AS SELECT * FROM TABEL_KARYAWAN 
CREATE PROC TAMPIL_JABATAN AS SELECT * FROM TABEL_JABATAN 
CREATE PROC TAMPIL_KELUARGA_KARYAWAN AS SELECT * FROM TABEL_KELUARGA_KARYAWAN 
CREATE PROC TAMPIL_ADMINISTRASI AS SELECT * FROM TABEL_ADMINISTRASI
--
EXEC TAMPIL_KARYAWAN
EXEC TAMPIL_JABATAN
EXEC TAMPIL_KELUARGA_KARYAWAN
EXEC TAMPIL_ADMINISTRASI 
--4
CREATE PROC TAMPIL_KARYAWAN_SEBAGIAN AS SELECT KODE_KARYAWAN, NAMA_KARYAWAN, TANGGAL_LAHIR, ALAMAT FROM TABEL_KARYAWAN RETURN
EXEC TAMPIL_KARYAWAN_SEBAGIAN 
--5
CREATE PROC TAMPIL_KELUARGA_KARYAWAN_VARIABEL @KY CHAR(10) AS SELECT * FROM TABEL_KELUARGA_KARYAWAN WHERE KODE_KARYAWAN = @KY RETURN
EXEC TAMPIL_KELUARGA_KARYAWAN_VARIABEL 'KY02' 
--6
CREATE PROC UBAH_KARYAWAN @NAMA CHAR(20), @NM CHAR(20) AS UPDATE TABEL_KARYAWAN SET NAMA_KARYAWAN = @NAMA WHERE NAMA_KARYAWAN = @NM RETURN
-- 
EXEC UBAH_KARYAWAN 'JONI', 'BEN' 
--7
CREATE PROC UBAH_KELUARGA_KARYAWAN @PT CHAR(10), @PEN CHAR(10) AS UPDATE TABEL_KELUARGA_KARYAWAN SET PENDIDIKAN_TERAKHIR = @PT WHERE PENDIDIKAN_TERAKHIR = @PEN RETURN
--
EXEC UBAH_KELUARGA_KARYAWAN 'S1', 'D4' 
--8
CREATE PROC HAPUS_KELUARGA_KARYAWAN @KY CHAR(10) AS DELETE FROM TABEL_KELUARGA_KARYAWAN WHERE KODE_KARYAWAN = @KY RETURN
--
EXEC HAPUS_KELUARGA_KARYAWAN 'KY05'
--9
CREATE TRIGGER INFO_KARYAWAN ON TABEL_KARYAWAN FOR INSERT AS PRINT 'DATA KARYAWAN BERHASIL DIMASUKKAN!'
CREATE TRIGGER INFO_JABATAN ON TABEL_JABATAN FOR INSERT AS PRINT 'DATA JABATAN BERHASIL DIMASUKKAN!'
CREATE TRIGGER INFO_KELUARGA_KARYAWAN ON TABEL_KELUARGA_KARYAWAN FOR INSERT AS PRINT 'DATA KELUARGA KARYAWAN BERHASIL DIMASUKKAN!'
CREATE TRIGGER INFO_ADMINISTRASI ON TABEL_ADMINISTRASI FOR INSERT AS PRINT 'DATA ADMINISTRASI BERHASIL DIMASUKKAN!'

CREATE TRIGGER INFO_UBAH_KELUARGA_KARYAWAN ON TABEL_KELUARGA_KARYAWAN FOR UPDATE AS PRINT 'DATA KELUARGA KARYAWAN BERHASIL DIUBAH!'
SELECT * FROM inserted 
SELECT * FROM deleted 

CREATE TRIGGER INFO_HAPUS_KELUARGA_KARYAWAN ON TABEL_KELUARGA_KARYAWAN FOR DELETE AS PRINT 'DATA KELUARGA KARYAWAN BERHASIL DIHAPUS!'